clc
clear
close all
%% Points cloud :
% I = textscan ('skull_cc.obj');   % fread
filename_com  =  'Heart_Fine_subdivision300' ; 
filename_node =  [ filename_com , '.node' ] ; % 'ellipsoid_2502.node' ;  
filename_ele  =  [ filename_com , '.ele' ] ; 

fid = fopen(  filename_node  );

x = [] ; %% 
y = [] ; %% 
z = [] ; %% 

vp_ind = [];  vn_ind = []; 
iter = 0 ;  
while( ~feof(fid) )
    SS = fgets(fid) ; 
    iter = iter + 1; 
    if( iter > 1.1  )
       %% scanf(SS,'v %f//%f %f//%f %f//%f',a,b,c,d,e,f)
        C = textscan(SS,  '%d %f %f %f' ) ;  %  
        x = [ x , C{2}/30 /25.0 ] ;
        y = [ y , C{3}/30 /25.0 ] ;
        z = [ z , C{4}/30 /25.0 ] ;
    end
    %     // S = fscanf(fid,'%s');
end

fclose(fid);

%% 
fid = fopen(  filename_ele  );
t = [] ; iter = 0 ;  
while( ~feof(fid) )
    SS = fgets(fid) ; 
    iter = iter + 1 ; %% 
    if( iter > 1.1 )
        C = textscan(SS,  '%d %d %d %d %d' ) ;  %  
        t = [ t ; [ C{2} C{3}  C{4}  C{5}  ] ];
    end
    %     // S = fscanf(fid,'%s');
end
t = t + 1; 
fclose(fid); 

%% 
p = [x' y' z'] ; 
figure(1);
hold on
axis equal
title('Points Cloud','fontsize',14)
data = p ;
plot3( data(:,1),data(:,2),data(:,3),'g.') %%  
camproj('perspective') ; 
% t = delaunay(x,y,z);
%% plot of the oyput triangulation
figure(4)
hold on
title('Output Triangulation','fontsize',14)
light
lighting phong
% trisurf( t , data(:,1) , data(:,2),data(:,3) , 'facecolor' , 'c' , 'edgecolor' , 'b' ) ;  %plot della superficie trattata
% trisurf( t , data(:,1) , data(:,2),data(:,3) , 'facecolor' , 'y' , 'edgecolor' , 'none' ) ;  %plot della superficie trattata
% trisurf( t , data(:,1) , data(:,2),data(:,3) , 'facecolor' , 'b' , 'edgecolor' , 'b' ) ;  %plot della superficie trattata
trisurf( t(:,1:3) , data(:,1) , data(:,2),data(:,3) , 'facecolor' , [0.8,0.8,0.8]  ) ;  %plot della superficie trattata
plot3( data(:,1),data(:,2),data(:,3),'g.') %%  
trisurf( t(:,2:4) , data(:,1) , data(:,2),data(:,3) , 'facecolor' , [0.8,0.0,0.0]   ) ;  %plot della superficie trattata
trisurf( t(:,[1 2 4]) , data(:,1) , data(:,2),data(:,3) , 'facecolor' , [0.0,0.8,0.0]  ) ;  %plot della superficie trattata
trisurf( t(:,[1 3 4]) , data(:,1) , data(:,2),data(:,3) , 'facecolor' , [0.0,0.0,0.8]  ) ;  %plot della superficie trattata
axis equal ; camproj('perspective') ; 
axis vis3d ; camproj('perspective') ; 
daspect([1 1 1]) ; camproj('perspective') ; 
axis on;
xlabel('x')
ylabel('y')
%%
% %% plot of the oyput triangulation
fid = fopen([ filename_ele( 1 : strfind(filename_ele,'.')-1 ) , '_normalized', filename_ele(strfind(filename_ele,'.'):end) ] , 'w' );  % % 
t = [ 1:size(t,1)  ; t' ] - 1 ; 
fprintf(fid , '%d  %d  %d\n' ,  size(t,2) , 4 , 0 ) ; % 
fprintf(fid , '%d  %d  %d  %d  %d\n' ,  t ) ; % 
fprintf(fid , '## Generated by Matlab \n \n'  ) ;
fclose(fid);

%%
% %% plot of the oyput triangulation
fid = fopen([ filename_node( 1 : strfind(filename_node,'.')-1 ) , '_normalized', filename_node(strfind(filename_node,'.'):end) ] , 'w' );  % % 
data = [ 0:size(data,1)-1  ; data' ] ; 
fprintf(fid , '%d  %d  %d  %d\n' ,  size(data,2) , 3 , 0 , 0 ) ; % 
fprintf(fid , '%d  %d  %d  %d\n' ,  data ) ; % 
fprintf(fid , '## Generated by Matlab \n \n'  ) ;
fclose(fid); 
% 
% 
% point_cloud = [x;y;z] ;
% face_triangle_index   = t' ; 
% normal_triangle_index = t' ; 
% normal_orignal        = [ nx ;ny ;nz ] ;
% 
% faces_index = [  face_triangle_index(1,:) ;normal_triangle_index(1,:);... 
%                  face_triangle_index(2,:) ;normal_triangle_index(2,:);...
%                  face_triangle_index(3,:) ;normal_triangle_index(3,:)] ; % ; t // 
% % 
% %
% fid = fopen([ 'skull_cc_with_normal_',num2str(300),'.obj'] , 'w' );  %
% fprintf(fid,'vt %f %f\n', [0,0] );
% fprintf(fid,'v  %f %f %f\n' , point_cloud ); 
% fprintf(fid,'vn %f %f %f\n', vertex_normal );
% fprintf(fid,'f %d/1/%d %d/1/%d %d/1/%d\n',  faces_index );
% % fprintf(fid,'f %d %d %d\n',  faces_index );
% fclose(fid);
% % 